### ISSUE TITLE
회원가입 페이지 만들기

### ISSUE THREAD

**Issue by hyooniee** [VuehappyJob20241219/octfair2#19]
* 적용 페이지 : 회원가입 페이지

## 내용
회원가입 페이지 구현

## TODO
- [ ] 회원가입 버튼 클릭시 모달창 활성화
- [ ] 필수 입력값은 유효성 검사하기
- [ ] 아이디 중복확인 버튼 
- [ ] 주소 API 구현
