### ISSUE TITLE
애드온(배경/음악/눈/점심) 개선

### ISSUE THREAD

**Issue by it-is-wanthefull** [VuehappyJob20241219/octfair2#47]
* 적용 페이지 : 사이드바 페이지

## 내용
![image](https://github.com/user-attachments/assets/956a114d-6dd4-4d83-9851-0d70366cfeb1)

## TODO
- [x] ON <-> OFF 가능하게 개선
- [x] 음악/배경 랜덤하게 나오게 개선 (AddOn파일에 명시해둔 목록 중에서만 랜덤)
- [x] 눈 애니메이션 쌓일 수 있게 개선
